name: quickrecord
description: The app for sending voice messages in to Zachnology Tech Reviews
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^4.0.0+4
  permission_handler: ^7.2.0
  share: ^0.6.5+4
  app_settings: ^4.0.4
  eva_icons_flutter: ^2.0.1
  get_version: ^0.2.2
  vibration: ^1.7.3
  intl: ^0.16.1
  mailto: ^1.1.0
  quick_actions: ^0.4.0+10
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: ZachnologyEuclid
      fonts:
        - asset: fonts/ZachnologyEuclid.ttf
  assets:
    - assets/zachnology.png
    - assets/173012.png
  uses-material-design: true